### ISSUE TITLE
sonatanfv/sonata-fw-vnf image is broken

### ISSUE THREAD

**Issue by knodir** [sonata-nfv/son-examples#81]
[start_fw.sh#L20](https://github.com/sonata-nfv/son-examples/blob/master/vnfs/sonata-fw-vnf-docker/start_fw.sh#L20) inside Docker image assumes interface names to be `(fwin, fwout)`, while during actual sonata-fw-service-emu project creation the interface names are listed as `(input, output)` (see [fw-vnf-vnfd.yml#L44](https://github.com/sonata-nfv/son-examples/blob/master/service-projects/sonata-fw-service-emu/sources/vnf/fw-vnf/fw-vnf-vnfd.yml#L44
)).

When I create `sonata-fw-service-emu` project, I can actually see `could not open network device fwin (No such device)` (resp. fwout) in `ovs-vsctl show` output.

```
$ son-package --project sonata-fw-service-emu -n sonata-fw-service
...
$ curl -i -X POST -F package=@sonata-fw-service.son http://127.0.0.1:5000/packages
...
$ curl -X POST http://127.0.0.1:5000/instantiations -d "{}"
...
$ sudo docker exec -it mn.fw /bin/bash 
$ root@fw:~# ovs-vsctl show
112e0b1d-d48c-4bcd-a304-af8495364b9b
    Bridge "ovs1"
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        fail_mode: secure
        Port "ovs1"
            Interface "ovs1"
                type: internal
        Port fwin
            Interface fwin
                error: "could not open network device fwin (No such device)"
        Port fwout
            Interface fwout
                error: "could not open network device fwout (No such device)"
    ovs_version: "2.5.0"
```

I tried this fix [start_fw.sh#L20](https://github.com/sonata-nfv/son-examples/blob/master/vnfs/sonata-fw-vnf-docker/start_fw.sh#L20)
```
- declare -a PORTS=("fwin" "fwout")
+ declare -a PORTS=("input" "output")
```
and things started working as expected, i.e., I don't see `No such device` error in `ovs-vsctl show` and when I deployed `sonata-fw-service-emu` project similar to [Example-3](https://github.com/sonata-nfv/son-emu/wiki/Example-3) `client <-> server` ping works.

**Comment by mpeuster** [comment]
I would propose a fix the other way around and change https://github.com/sonata-nfv/son-examples/blob/master/service-projects/sonata-fw-service-emu/sources/vnf/fw-vnf/fw-vnf-vnfd.yml#L44 to:

```
virtual_links:
  - id: "mgmt"
    connectivity_type: "E-LAN"
    connection_points_reference:
      - "vdu01:eth0"
      - "mgmt"
  - id: "fwin"
    connectivity_type: "E-Line"
    connection_points_reference:
      - "vdu01:eth1"
      - "fwin"
  - id: "fwout"
    connectivity_type: "E-Line"
    connection_points_reference:
      - "vdu01:eth2"
      - "fwout"
```

I assume it will do the job as well. The reason for this is that I remember that there could be problems if we run multiple containers having the same interface names `input` and `output` ... at least if someone tries this vTC VNF with its strange kernel patch :-)

@stevenvanrossem what do you think?

**Comment by stevenvanrossem** [comment]
I agree to change the interface names in the `fw-vnf` descriptor, 
I definined a different interface name in:   https://github.com/sonata-nfv/son-examples/blob/master/service-projects/sonata-fw-service-emu/sources/vnf/fw-vnf/fw-vnf-vnfd.yml#L66

done by: https://github.com/sonata-nfv/son-examples/pull/82

the networking commands should then be:
`son-emu-cli network add -b -src client:client-eth0 -dst fw:fwin`
`son-emu-cli network add -b -src fw:fwout -dst server:server-eth0`

Also, I updated the examples in the wiki to not use the deprecated son-push tool. (instead using the dummy gatekeeper directly as default)
Additionally, I refer to this page to describe the use of `son-access push`
https://github.com/sonata-nfv/son-emu/wiki/Dummy-Gatekeeper-API
@dang03 can you quickly review this, to make sure this is the latest wow, or is this described already somewhere else?
